# Generated by Django 6.1.1 on 2026-09-17 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('organizations', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_project_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('original_cost', models.BigIntegerField(blank=True, help_text='Original project cost in paise', null=True)),
                ('current_cost', models.BigIntegerField(blank=True, help_text='Current/revised project cost in paise', null=True)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('current_expenditure', models.BigIntegerField(blank=True, help_text='Cumulative expenditure in paise', null=True)),
                ('original_start_date', models.DateField(blank=True, null=True)),
                ('current_start_date', models.DateField(blank=True, null=True)),
                ('original_completion_date', models.DateField(blank=True, null=True)),
                ('current_completion_date', models.DateField(blank=True, null=True)),
                ('current_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('source_status', models.CharField(blank=True, help_text='Status as reported by source', max_length=255)),
                ('platform_status', models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('contractor_name', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True)),
                ('source_updated_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organizations.department')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='locations.district')),
                ('ministry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organizations.ministry')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organizations.organization')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='organizations.sector')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.datasource')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='locations.state')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot_date', models.DateField()),
                ('project_cost', models.BigIntegerField(blank=True, null=True)),
                ('revised_cost', models.BigIntegerField(blank=True, null=True)),
                ('expenditure', models.BigIntegerField(blank=True, null=True)),
                ('physical_progress', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('source_status', models.CharField(blank=True, max_length=255)),
                ('raw_record_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='projects.project')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sources.datasource')),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('COST_CHANGED', 'Cost Changed'), ('PROGRESS_CHANGED', 'Progress Changed'), ('EXPENDITURE_CHANGED', 'Expenditure Changed'), ('COMPLETION_DATE_CHANGED', 'Completion Date Changed'), ('START_DATE_CHANGED', 'Start Date Changed'), ('STATUS_CHANGED', 'Status Changed'), ('OTHER_FIELD_CHANGED', 'Other Field Changed')], max_length=40)),
                ('field_name', models.CharField(max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('change_amount', models.FloatField(blank=True, null=True)),
                ('change_percentage', models.FloatField(blank=True, null=True)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='projects.project')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='projects.projectsnapshot')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['state'], name='projects_pr_state_i_bb0c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['sector'], name='projects_pr_sector__64e5ae_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['ministry'], name='projects_pr_ministr_350645_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['platform_status'], name='projects_pr_platfor_7e5f45_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['current_progress'], name='projects_pr_current_6d0905_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['current_cost'], name='projects_pr_current_44cb30_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsnapshot',
            index=models.Index(fields=['project', 'snapshot_date'], name='projects_pr_project_d119a3_idx'),
        ),
        migrations.AddIndex(
            model_name='projectsnapshot',
            index=models.Index(fields=['raw_record_hash'], name='projects_pr_raw_rec_69eca1_idx'),
        ),
        migrations.AddIndex(
            model_name='projectchange',
            index=models.Index(fields=['project', 'change_type'], name='projects_pr_project_9e043d_idx'),
        ),
        migrations.AddIndex(
            model_name='projectchange',
            index=models.Index(fields=['detected_at'], name='projects_pr_detecte_2be366_idx'),
        ),
    ]
