# Generated by Django 6.1.1 on 2026-09-17 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('organization', models.CharField(max_length=255)),
                ('source_type', models.CharField(choices=[('CSV', 'CSV'), ('XLSX', 'XLSX'), ('JSON', 'JSON'), ('XML', 'XML'), ('API', 'API'), ('PDF', 'PDF'), ('WEB', 'Web')], max_length=20)),
                ('base_url', models.URLField(blank=True)),
                ('access_method', models.CharField(choices=[('MANUAL_UPLOAD', 'Manual Upload'), ('SCHEDULED_DOWNLOAD', 'Scheduled Download'), ('API_PULL', 'API Pull')], max_length=30)),
                ('update_frequency', models.CharField(blank=True, help_text='e.g. Monthly, Quarterly', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_successful_sync', models.DateTimeField(blank=True, null=True)),
                ('last_failed_sync', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
