# Generated by Django 6.1.1 on 2026-09-18 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0002_raw_ingestion_record'),
        ('projects', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('document_type', models.CharField(choices=[('FLASH_REPORT', 'Monthly Flash Report (PDF)'), ('SUMMARY_SHEET', 'Summary Sheet'), ('PROJECT_REPORT', 'Detailed Project Report'), ('DATA_EXPORT', 'Data Export'), ('ANNEXURE', 'Statistical Annexure'), ('OTHER', 'Other Official Document')], default='FLASH_REPORT', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='sources.datasource')),
                ('ingestion_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='ingestion.ingestionrun')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='projects.project')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
