# Generated by Django 6.1.1 on 2026-09-17 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngestionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL_SUCCESS', 'Partial Success'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('records_found', models.IntegerField(default=0)),
                ('records_inserted', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_rejected', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_runs', to='sources.datasource')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DataQualityIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_record_ref', models.CharField(blank=True, max_length=255)),
                ('problem_description', models.TextField()),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Needs Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CORRECTED', 'Corrected'), ('DUPLICATE', 'Marked Duplicate')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_issues', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
