# Generated by Django 6.1.1 on 2026-09-17 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawIngestionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_record_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_payload', models.JSONField(help_text='Original source row dict, pre-normalization')),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('source_file', models.CharField(blank=True, max_length=500)),
                ('was_accepted', models.BooleanField(default=False)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ingestion_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingestion.ingestionrun')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_hash'], name='ingestion_r_content_f6110f_idx'), models.Index(fields=['ingestion_run', 'external_record_id'], name='ingestion_r_ingesti_655615_idx')],
            },
        ),
    ]
